In [2]:
import numpy as np

# Inputs, weights, and biases for previous layers
inputs = [[1, 2, 3, 2.5],
          [2., 5., -1., 2],
          [-1.5, 2.7, 3.3, -0.8]]

weights = [[0.2, 0.8, -0.5, 1],  # first weight matrix : 3X4 
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]

biases = [2, 3, 0.5]    # 1st bias matrix : (3X1) 

weights2 = [[0.1, -0.14, 0.5],  # second weight matrix : 3X3 
            [-0.5, 0.12, -0.33],
            [-0.44, 0.73, -0.13]]

biases2 = [-1, 2, -0.5]  # 2nd bias matrix : (3X1)
weights3 = [[0.2, 0.8],  # weights matrix: 3x2
            [0.5, -0.91],
            [0.9, -0.95]]
biases3 = [-1, 2]

# Adding Layer 4
weights4 = [[0.3],  # weights matrix: 2x1 (2 neurons from Layer 3 to 1 neuron in Layer 4)
            [-0.8]]
biases4 = [0.5]  # Single bias value for Layer 4

# Convert everything into numpy arrays
inputs_array = np.array(inputs)
weights_array = np.array(weights)
biases_array = np.array(biases)
weights2_array = np.array(weights2)
biases2_array = np.array(biases2)
weights3_array = np.array(weights3)
biases3_array = np.array(biases3)
weights4_array = np.array(weights4)
biases4_array = np.array(biases4)

# Calculate the output of the first layer
layer1_outputs = np.dot(inputs_array, weights_array.T) + biases_array
print("Layer 1 Output:\n", layer1_outputs)

# Calculate the output of the second layer
layer2_outputs = np.dot(layer1_outputs, weights2_array.T) + biases2_array
print("Layer 2 Output:\n", layer2_outputs)

# Calculate the output of the third layer
layer3_outputs = np.dot(layer2_outputs, weights3_array) + biases3_array
print("Layer 3 Output:\n", layer3_outputs)

# Calculate the output of the fourth layer
layer4_outputs = np.dot(layer3_outputs, weights4_array) + biases4_array
print("Layer 4 Output:\n", layer4_outputs)


Layer 1 Output:
 [[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]
Layer 2 Output:
 [[ 0.5031  -1.04185 -2.03875]
 [ 0.2434  -2.7332  -5.7633 ]
 [-0.99314  1.41254 -0.35655]]
Layer 3 Output:
 [[-3.25518    5.287376 ]
 [-7.50489   10.157067 ]
 [-0.813253   0.2587991]]
Layer 4 Output:
 [[-4.7064548 ]
 [-9.8771206 ]
 [ 0.04898482]]


In [4]:
import numpy as np 
import pandas as pd

In [6]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def relu(x):
    return np.maximum(0, x)

In [8]:
# Generate a simple dataset
np.random.seed(42)
X = np.random.rand(100, 2)  # 100 points with 2 features (x1, x2)
y = (X[:, 0] + X[:, 1] > 1).astype(int)  # Label is 1 if x1 + x2 > 1, else 0

# Create a DataFrame for easy visualization
data = pd.DataFrame(X, columns=["x1", "x2"])
data["y"] = y
data

input_layer = 2
hidden_layer = 3
output_layer = 1

np.random.seed(42)
w1 = np.random.rand(input_layer,hidden_layer)#weights for the input to hidden
b1 = np.zeros((1,hidden_layer))# bias for the hidden layer 

w2 = np.random.rand(hidden_layer,output_layer)#weight for the hidden to output
b2 = np.zeros((1,output_layer))

def forword(x):
    z1 = np.dot(X,w1)+b1
    a1 = relu(z1)


    z2 = np.dot(a1,w2)+b1
    a2 = sigmoid(z2)

    return  a1,a2
a1,a2 = forword(X)
print("Hidden Layer Output (A1):", a1[:5])
print("Output Layer Prediction (A2):", a2[:5])

Hidden Layer Output (A1): [[0.70943349 0.5044098  0.42246732]
 [0.63255308 0.789319   0.62920257]
 [0.15182268 0.17266721 0.13853899]
 [0.54029834 0.19036055 0.17763558]
 [0.64903534 0.68196116 0.55046799]]
Output Layer Prediction (A2): [[0.6752584  0.6752584  0.6752584 ]
 [0.7500077  0.7500077  0.7500077 ]
 [0.56012183 0.56012183 0.56012183]
 [0.57518737 0.57518737 0.57518737]
 [0.72297991 0.72297991 0.72297991]]


In [2]:
import numpy as np
import pandas as pd

# Set random seed for reproducibility
np.random.seed(42)

# Generate random IQ levels (1D array: 100 samples)
iq_levels = np.random.normal(100, 15, 100).astype(int)  # Mean=100, Std=15

# Generate random CGPA values (1D array: 100 samples)
cgpa = np.round(np.random.uniform(5.0, 10.0, 100), 2)

# Define placement labels based on IQ and CGPA
# Students with IQ > 110 and CGPA > 8.0 are more likely to get placed
placed = np.array([1 if iq > 110 and gpa > 8.0 else 0 for iq, gpa in zip(iq_levels, cgpa)])

# Combine into a pandas DataFrame
data = pd.DataFrame({
    "IQ Level": iq_levels,
    "CGPA": cgpa,
    "Placed": placed
})


data

IQ Level  CGPA  Placed
0        107  7.09       0
1         97  6.11       0
2        109  5.60       0
3        122  6.69       0
4         96  9.71       0
..       ...   ...     ...
95        78  6.22       0
96       104  9.87       0
97       103  6.97       0
98       100  9.46       0
99        96  8.16       0

[100 rows x 3 columns]

In [4]:
class Activation_Relu:
    def forward(self, inputs):
        self.output = np.maximum(0, inputs)

class Activation_Tanh:
    def forward(self, inputs):
        self.output = np.tanh(inputs)

class Activation_softmax:
    def forward(self, inputs):
        exp_values = np.exp(inputs - np.max(inputs, axis=1, keepdims=True))
        probabilities = exp_values / np.sum(exp_values, axis=1, keepdims=True)
        self.output = probabilities

class Actiavation_sigmoid:
    def forward(self, inputs):
        self.output = 1 / (1 + np.exp(-inputs))

class Dense_layer:
    def __init__(self, n_inputs, n_neurons):
        self.weights = 0.01 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))

    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases

In [14]:
# Prepare dataset
X = data[["IQ Level", "CGPA"]].values  # Use the raw data (without normalization)
y = data["Placed"].values.reshape(-1, 1)  # Target (reshaped for binary classification)


# Layer 1
dense1 = Dense_layer(2, 3)
activation1 = Activation_Relu()
dense1.forward(X)
activation1.forward(dense1.output)
print("Activation 1 output:", activation1.output[:5])

# Layer 2
dense2 = Dense_layer(3, 5)
activation2 = Activation_Tanh()
dense2.forward(activation1.output)
activation2.forward(dense2.output)
print("Activation 2 output:", activation2.output[:5])

# Layer 3
dense3 = Dense_layer(5, 2)
activation3 = Activation_softmax()
dense3.forward(activation2.output)
activation3.forward(dense3.output)
print("Activation 3 output:", activation3.output[:5])

# Layer 4 (Final Layer)
dense4 = Dense_layer(2, 1)
activation4 = Actiavation_sigmoid()
dense4.forward(activation3.output)
activation4.forward(dense4.output)
print("Activation 4 output:", activation4.output[:5])
rounded_output = np.round(activation4.output)



Activation 1 output: [[0.85971189 1.55863497 0.        ]
 [0.77259509 1.41916375 0.        ]
 [0.8411723  1.61944141 0.        ]
 [0.95049936 1.80434584 0.        ]
 [0.84276299 1.33302842 0.        ]]
Activation 2 output: [[-0.00412819  0.01565664  0.00021115 -0.01258852  0.00978278]
 [-0.00381872  0.01422721  0.00025569 -0.01144096  0.00895765]
 [-0.00459562  0.01612104  0.00054368 -0.0129712   0.01042113]
 [-0.00504218  0.01799864  0.00052304 -0.01447967  0.01154541]
 [-0.00289827  0.01369268 -0.00048876 -0.01099022  0.00783693]]
Activation 3 output: [[0.49993839 0.50006161]
 [0.49994406 0.50005594]
 [0.4999368  0.5000632 ]
 [0.49992938 0.50007062]
 [0.49994561 0.50005439]]
Activation 4 output: [[0.50204864]
 [0.50204864]
 [0.50204864]
 [0.50204864]
 [0.50204864]]
Rounded Output: [[1.]
 [1.]
 [1.]
 [1.]
 [1.]]
